In [1]:
def get_ticker_data(pair="USDT_BTC"):
    import json
    import numpy as np
    import os
    import pandas as pd
    import urllib
    
    # connect to poloniex's API
    url = 'https://poloniex.com/public?command=returnChartData&currencyPair={}&start=1356998100&end=9999999999&period=300'
    
    url_pair = url.format(pair)
    
    # parse json returned from the API to Pandas DF
    openUrl = urllib.request.urlopen(url_pair)
    r = openUrl.read()
    openUrl.close()
    d = json.loads(r.decode())
    df = pd.DataFrame(d)
    
    original_columns=[u'close', u'date', u'high', u'low', u'open']
    new_columns = ['Close','Timestamp','High','Low','Open']
    df = df.loc[:,original_columns]
    df.columns = new_columns
    return df

In [2]:
USDT_BTC = get_ticker_data("USDT_BTC")
USDT_ETH = get_ticker_data("USDT_ETH")

In [75]:
print("USDT-BTC size" + str(USDT_BTC.shape))
print("USDT-ETH size" + str(USDT_ETH.shape))

USDT-BTC size(339219, 5)
USDT-ETH size(290413, 5)

In [4]:
USDT_ETH

             Close   Timestamp        High         Low        Open
0         1.750000  1439014500    0.330000    1.610000    0.330000
1         1.850000  1439014800    1.850000    1.850000    1.850000
2         1.850000  1439015100    1.850000    1.850000    1.850000
3         1.850000  1439015400    1.850000    1.850000    1.850000
4         1.850000  1439015700    1.850000    1.850000    1.850000
5         1.850000  1439016000    1.850000    1.850000    1.850000
6         1.850000  1439016300    1.850000    1.850000    1.850000
7         1.710000  1439016600    1.710000    1.710000    1.710000
8         1.710000  1439016900    1.710000    1.710000    1.710000
9         1.710000  1439017200    1.710000    1.710000    1.710000
10        1.710000  1439017500    1.710000    1.710000    1.710000
11        1.750000  1439017800    1.750000    1.750000    1.750000
12        0.500000  1439018100    1.750000    0.500000    1.750000
13        0.500000  1439018400    0.500000    0.500000    0.500000
14        1.850000  1439018700    1.850000    1.850000    1.850000
15        1.850000  1439019000    1.850000    1.850000    1.850000
16        1.850000  1439019300    1.850000    1.850000    1.850000
17        1.850000  1439019600    1.850000    1.850000    1.850000
18        1.850000  1439019900    1.850000    1.850000    1.850000
19        1.850000  1439020200    1.850000    1.850000    1.850000
20        1.850000  1439020500    1.850000    1.850000    1.850000
21        1.850000  1439020800    1.850000    1.850000    1.850000
22        1.850000  1439021100    1.850000    1.850000    1.850000
23        1.850000  1439021400    1.850000    1.850000    1.850000
24        1.850000  1439021700    1.850000    1.850000    1.850000
25        1.850000  1439022000    1.850000    1.850000    1.850000
26        1.850000  1439022300    1.850000    1.850000    1.850000
27        1.850000  1439022600    1.850000    1.850000    1.850000
28        1.850000  1439022900    1.850000    1.850000    1.850000
29        1.500000  1439023200    1.700000    1.500000    1.700000
...            ...         ...         ...         ...         ...
292455  699.933169  1526751000  701.728614  699.602600  700.963221
292456  701.313100  1526751300  701.321000  699.960819  699.960819
292457  699.745000  1526751600  701.019277  699.220925  699.989700
292458  700.671219  1526751900  700.671219  699.266221  699.999000
292459  698.858647  1526752200  699.250500  698.857427  699.250500
292460  700.289700  1526752500  701.359803  699.502900  699.502900
292461  700.297800  1526752800  701.685100  700.297800  701.685100
292462  701.678100  1526753100  701.726100  700.742641  701.723180
292463  700.785000  1526753400  701.736421  700.785000  700.990000
292464  700.652249  1526753700  701.664700  700.652249  701.664700
292465  701.251500  1526754000  702.020100  701.239900  701.600000
292466  702.767602  1526754300  703.500000  702.022343  702.736421
292467  704.110000  1526754600  704.146124  702.769800  703.500000
292468  703.502500  1526754900  704.490000  703.500000  704.141854
292469  702.094900  1526755200  704.175511  702.094900  704.174500
292470  702.783526  1526755500  702.783526  701.000000  701.782400
292471  703.222180  1526755800  703.222180  703.222180  703.222180
292472  701.016600  1526756100  703.140379  701.009764  703.140379
292473  701.741579  1526756400  701.741579  699.609925  701.708980
292474  701.689646  1526756700  701.742800  701.689646  701.742800
292475  701.689646  1526757000  701.689646  701.689646  701.689646
292476  701.689646  1526757300  701.689646  701.689646  701.689646
292477  702.379880  1526757600  702.379880  702.379880  702.379880
292478  701.296121  1526757900  702.949454  701.296121  702.200100
292479  700.666790  1526758200  702.085097  700.666790  701.302700
292480  702.000500  1526758500  702.735345  700.708421  700.708421
292481  701.566400  1526758800  702.420100  700.984213  702.270100
292482  702.001000  1526759100  702.771600  700.995662  700.995662
292483  703.275200  1526759400  703.436513  701.352877  702.001000
292484  702.050800  1526759700  702.050800  702.050800  702.050800

[292485 rows x 5 columns]

In [ ]:


tweetCriteria = got.manager.TweetCriteria().setUsername('barackobama').setMaxTweets(1)
tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]